package com.deu.cengonline.util;

public enum ErrorName {
	COURSE_NOT_FOUND,
	ANNOUNCEMENT_NOT_FOUND,
	POST_NOT_FOUND,
	ASSIGNMENT_NOT_FOUND,
	SUBMISSION_NOT_FOUND,
	USER_NOT_FOUND,
	ROLE_NOT_FOUND,
	FAILED_LOGIN,
	EMAIL_IN_USE,
	MESSAGE_TO_YOURSELF,
	NO_USER_YET,
	ALREADY_ATTENDED,
	NOT_ALLOWED_GET,
	ALREADY_SUBMITTED
}
